services:
    db:
        container_name: kiwi_db
        image: mariadb:latest
        command:
            --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - db_data:/var/lib/mysql:rw
        restart: always
        environment:
            # checkov:skip=CKV_SECRET_6:Base64 High Entropy String
            MYSQL_ROOT_PASSWORD: kiwi-1s-aw3s0m3
            MYSQL_DATABASE: kiwi
            MYSQL_USER: kiwi
            MYSQL_PASSWORD: kiwi

    web:
        container_name: kiwi_web
        depends_on:
            - db
        restart: always
        image: pub.kiwitcms.eu/kiwitcms/kiwi:latest
        ports:
            - 8080:8080
            - 443:8443
        volumes:
            - uploads:/Kiwi/uploads:rw
            - static_files:/Kiwi/static:rw
            - ./branding:/Kiwi/custom_static:ro
        environment:
            KIWI_DB_HOST: db
            KIWI_DB_PORT: 3306
            KIWI_DB_NAME: kiwi
            KIWI_DB_USER: kiwi
            KIWI_DB_PASSWORD: kiwi
            STATICFILES_DIRS: /Kiwi/custom_static
        cap_drop:
          - ALL

volumes:
    db_data:
        driver: local
    uploads:
        driver: local
    static_files:
        driver: local